version: "3.8"

services:
  premd:
    container_name: premd
    image: ${PREM_DAEMON_IMAGE}
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PREM_REGISTRY_URL=${PREM_REGISTRY_URL}
      - SENTRY_DSN=${SENTRY_DSN}

  prem_app:
    container_name: prem_app
    image: ${PREM_APP_IMAGE}
    restart: on-failure
    environment:
      - VITE_DESTINATION=browser
      - VITE_IS_PACKAGED=true

  caddy:
    container_name: caddy
    image: caddy:2.6.4-alpine@sha256:4dfec6c3b22c36b63ea4a3633c7cdbdaa9926d1324c27db2b0e2b70ef9cd105a
    restart: on-failure
    ports:
      - 8080:8080
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
